# Generated by Django 5.2.8 on 2025-11-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_calendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
