# Generated by Django 5.2.8 on 2025-11-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='is_collapsed',
            field=models.BooleanField(default=False),
        ),
    ]
