# Generated by Django 5.2.8 on 2025-12-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_widget_is_collapsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='is_collapsed',
        ),
    ]
