# Generated by Django 5.2.8 on 2025-12-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_widget_is_collapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('list', 'Liste de liens'), ('note', 'Bloc-notes')], default='list', max_length=10),
        ),
    ]
