# Generated by Django 5.2.8 on 2025-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('list', 'Liste de liens'), ('note', 'Bloc-notes'), ('command', 'Lanceur de scripts')], default='list', max_length=10),
        ),
    ]
